package digitalwallet_sde3.service;

import digitalwallet_sde3.database.LedgerDatabase;
import digitalwallet_sde3.messaging.EventBus;
import digitalwallet_sde3.model.Account;
import digitalwallet_sde3.model.events.*;

import java.math.BigDecimal;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

/**
 * Manages accounts. Handles commands (events generated by the Saga Coordinator or Gateway).
 * It listens to `ledgerCommands` queue.
 */
public class AccountLedgerService {
    private final LedgerDatabase db;
    private final ExecutorService worker = Executors.newSingleThreadExecutor();

    public AccountLedgerService(LedgerDatabase db) {
        this.db = db;
        startEventLoop();
    }

    public void createAccount(String accountId, BigDecimal balance) {
        db.save(new Account(accountId, balance));
    }

    private void startEventLoop() {
        worker.submit(() -> {
            try {
                while (!Thread.currentThread().isInterrupted()) {
                    Event event = EventBus.getInstance().getLedgerCommandsQueue().take();
                    processLedgerCommand(event);
                }
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
            }
        });
    }

    private void processLedgerCommand(Event event) {
        if (event instanceof TransferRequestedEvent) {
            handleReserveFunds((TransferRequestedEvent) event);
        } else if (event instanceof FundsReservedEvent) {
            // Coordinator tells us it's time to credit the receiver
            handleCreditFunds((FundsReservedEvent) event);
        } else if (event instanceof FundsCreditedEvent) {
            // Coordinator tells us receiver got it, so commit sender's reservation
            handleCommitReservation((FundsCreditedEvent) event);
        } else if (event instanceof FundsRejectedEvent) {
            // Coordinator tells us something failed, rollback sender's reservation
            handleRollbackReservation((FundsRejectedEvent) event); // In this simplified domain, if receiver rejects, we shouldn't have one since Account B is always valid, but good to have for complete SMC.
        }
    }

    private void handleReserveFunds(TransferRequestedEvent cmd) {
        Account account = db.getAccount(cmd.getFromAccountId());
        
        if (account != null && account.reserveFunds(cmd.getAmount())) {
            System.out.println("[LEDGER] Reserved $" + cmd.getAmount() + " from " + cmd.getFromAccountId() + " for Saga: " + cmd.getSagaId().substring(0,8));
            // Publish Success back to Saga Coordinator
            EventBus.getInstance().publishToSagaCoordinator(new FundsReservedEvent(cmd.getSagaId(), cmd.getFromAccountId(), cmd.getAmount()));
        } else {
            System.out.println("[LEDGER] Failed to reserve $" + cmd.getAmount() + " from " + cmd.getFromAccountId() + " (Insufficient Funds). Saga: " + cmd.getSagaId().substring(0,8));
            // Publish Failure
            EventBus.getInstance().publishToSagaCoordinator(new FundsRejectedEvent(cmd.getSagaId(), cmd.getFromAccountId(), cmd.getAmount(), "INSUFFICIENT_FUNDS"));
        }
    }

    private void handleCreditFunds(FundsReservedEvent cmd) {
        // We need the ToAccountId, but the Reserved event doesn't carry it directly in this simplified model.
        // Wait, the SagaCoordinator issues the actual CREDIT command with the ToAccountId.
        // Let's assume the SagaCoordinator sends a new pseudo-event for this.
        // Actually, to keep it clean, the EventBus sends FundsReservedEvent to Coordinator, NOT to Ledger.
    }

    // Wait, the above event routing was a bit messy. 
    // Let's implement explicit handlers for the precise routing.
    
    // Commands From Coordinator to Ledger:
    // 1. TransferRequestedEvent -> (Ledger calls ReserveFunds)
    // 2. pseudo-CreditCommand -> (Ledger calls CreditFunds) -> we will use a specific object or overload.
    
    public void executeCredit(String toAccountId, BigDecimal amount, String sagaId) {
        Account account = db.getAccount(toAccountId);
        if (account != null) {
            account.creditFunds(amount);
            System.out.println("[LEDGER] Credited $" + amount + " to " + toAccountId + " for Saga: " + sagaId.substring(0,8));
            EventBus.getInstance().publishToSagaCoordinator(new FundsCreditedEvent(sagaId, toAccountId, amount));
        } else {
            // Account doesn't exist? Reject.
             EventBus.getInstance().publishToSagaCoordinator(new FundsRejectedEvent(sagaId, toAccountId, amount, "ACCOUNT_NOT_FOUND"));
        }
    }

    public void executeCommit(String fromAccountId, BigDecimal amount, String sagaId) {
        Account account = db.getAccount(fromAccountId);
        if (account != null) {
            account.commitReservedFunds(amount);
            System.out.println("[LEDGER] Committed $" + amount + " reserve on " + fromAccountId + " for Saga: " + sagaId.substring(0,8));
        }
    }

    public void executeRollback(String fromAccountId, BigDecimal amount, String sagaId) {
         Account account = db.getAccount(fromAccountId);
         if (account != null) {
             account.rollbackReservedFunds(amount);
             System.out.println("[LEDGER] Rolled Back $" + amount + " reserve on " + fromAccountId + " for Saga: " + sagaId.substring(0,8));
         }
    }

    public Account getAccountState(String accountId) {
        return db.getAccount(accountId);
    }

    public void shutdown() {
        worker.shutdownNow();
    }
}
